### ISSUE TITLE
Konami Code hint text appears an infinite number of times

### ISSUE THREAD

**Issue by Technetium-Hat** [Snektective/snektective.github.io#10]
when you click on the snek more than once the easter egg text appears more and more times. should only appear once. literally unusable.

/s

**Comment by Technetium-Hat** [comment]
lol

**Comment by 9hp** [comment]
fixed, thanks for telling me lmao
EDIT: its a feature

**Comment by Technetium-Hat** [comment]
EDIT: not actually fixed
EDIT: saw your edit

**Comment by Technetium-Hat** [comment]
ok ok i get it it's a feature
